### ISSUE TITLE
/usr/bin/ld: libpoly.a(controller.cpp.o):(.bss+0x8): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here

### ISSUE THREAD

**Issue by A-Siam** [polybar/polybar#2097]
### I'm using the AUR package
```yay -S polybar```
### error
```
/usr/bin/ld: libpoly.a(controller.cpp.o):(.bss+0x8): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: libpoly.a(bspwm.cpp.o):(.bss+0x0): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: libpoly.a(bspwm.cpp.o):(.bss+0x0): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: libpoly.a(i3.cpp.o):(.bss+0x0): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here
/usr/bin/ld: libpoly.a(socket.cpp.o):(.bss+0x0): multiple definition of `polybar::socket_util::make_unix_connection'; libpoly.a(bar.cpp.o):(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [bin/CMakeFiles/polybar.dir/build.make:115: bin/polybar] Error 1
make[1]: *** [CMakeFiles/Makefile2:625: bin/CMakeFiles/polybar.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: polybar-git
```

### Environment:
* Arch-linux
* WM: i3-gaps

**Comment by filiphe** [comment]
Got this issue after gcc was upgraded to 10.1.0. It worked on 9.3.0.

**Comment by A-Siam** [comment]
> Got this issue after gcc was upgraded to 10.1.0. It worked on 9.3.0.

this worked, i wish they could fix that

**Comment by StephanBischoff-Digle** [comment]
Manual build using Clang does work. Invoke cmake with `CXX=/bin/clang++ cmake ..`.

I'm on Arch with the Xmonad WM and Clang 10.0.0

**Comment by scrouthtv** [comment]
Related: https://gcc.gnu.org/gcc-10/porting_to.html
> A common mistake in C is omitting extern when declaring a global variable in a header file. GCC 10 defaults to -fno-common, which means a linker error will now be reported.

**Comment by scrouthtv** [comment]
If anyone else is having this issue on Arch you can solve it manually by downgrading to gcc 9.
Either downgrade if you still have the old cached version or download them from 
https://archive.archlinux.org/packages/g/gcc/gcc-9.3.0-1-x86_64.pkg.tar.zst
and
https://archive.archlinux.org/packages/g/gcc-libs/gcc-libs-9.3.0-1-x86_64.pkg.tar.zst

And install using `pacman -U gcc-9.3.0-1-x86_64.pkg.tar.zst gcc-libs-9.3.0-1-x86_64.pkg.tar.zst`. It's important to downgrade both at the same time because one depends on the other.

In the end I guess this is up to the polybar authors to change buildfiles or stick to the new default: 
> To fix this, use extern in header files when declaring global variables, and ensure each global is defined in exactly one C file.

**Comment by Lomadriel** [comment]
I made a fix in #2098.

@scrouthtv Downgrading the c library is quite dangerous since it'll make your applications/kernel unstable.
